name: GEN_DOC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_doc_changes:
   runs-on: ubuntu-latest
   outputs:
     doc_files: ${{ steps.check_doc_changes.outputs.doc_files }}
   steps:
     - if: github.event == pull_request
     - uses: actions/checkout@v2
     - name: Check if doc files were changed
       id: check_doc_changes_on_pr
       run: |
         git fetch -u origin master:master
         doc_files="$(git diff --name-only master | grep '\.md\|\.txt' || true)"
         echo "::set-output name=doc_files::$doc_files"
     - if: github.event == push
     - uses: actions/checkout@v2
     - name: Check if doc files were changed
       id: check_doc_changes_on_push
       run: |
         git fetch -u origin master:master
         doc_files="$(git diff --name-only master | grep '\.md\|\.txt' || true)"
         echo "::set-output name=doc_files::$doc_files"
   
  gen_doc:
    runs-on: ubuntu-latest
    needs: check_doc_changes
    if: ${{ needs.check_doc_changes.outputs.doc_files }}

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Generate Documentation.md
      run: |
        python Documentation/gen.py
        
    - name: Commit
    - if: github.event == push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git commit -m "Change file" -a
    
    - name: Push changes
    - if: github.event == push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
